---
title: "**Consultoria**"
bibliography:
  - references.bib
link-citations: yes
output:
  html_document:
    toc: false
---

```{css, echo = FALSE}
body {
  font-size: 2em;
}

div.main-container {
  max-width: 1280px;
  margin-left: auto;
  margin-right: auto;
}

.center {
  margin-left: auto;
  margin-right: auto;
}
```

<br>

# {#contato .unlisted .unnumbered}

<center>
  <div class="d-grid gap-2"">
    <button class="btn btn-secondary btn-lg" type="button" style="width:100%;font-size:1.1em">
      <span href="mailto:arthur_sf@icloud.com?subject=Cotação">`r library(fontawesome); paste0("Entre em contato! &nbsp; ", fa("envelope", margin_right = "0.1em"))`
      </span>
    </button>
  </div>
</center>

```{css, echo = FALSE}
.nav-pills>li>a:hover,
.nav-pills>li>a:focus,
.nav-pills>li.active>a,
.nav-pills>li.active>a:hover,
.nav-pills>li.active>a:focus{
   background-color: #2C3E50;
   }
.nav-pills > li {
    float:none;
    display:inline-block;
    zoom:1;
}
.nav-pills {
    text-align:center;
}
```

# {.tabset .tabset-fade .tabset-pills .tabset .justify-center}

## **Elaboração de projetos** {#projeto-de-pesquisa}

<br>

<div><center>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Objetivo geral </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Objetivos específicos </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Hipóteses </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Delineamento </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Aspectos éticos </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Critérios de elegibilidade </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Formatação </span>
</center></div>

<br>

### **`r library(fontawesome); fa("clipboard-list", margin_right = "0.1em")` Revisão de métodos**
<p>*Texto editável | Referências sugeridas*</p>

### **`r library(fontawesome); fa("comment-dots", margin_right = "0.1em")` Revisão de estilo científico**
<p>*Texto editável | Referências sugeridas*</p>

### **`r library(fontawesome); fa("book-medical", margin_right = "0.1em")` Revisão de aspectos éticos**
<p>*Texto editável*</p>

### **`r library(fontawesome); fa("list-ol", margin_right = "0.1em")` Formatação de referências**
<p>*Texto editável | Biblioteca de software gerenciador*</p>

### **`r library(fontawesome); fa("chalkboard-user", margin_right = "0.1em")` Mentoria**
<p>*Orientação*</p>

<!--script for generating HORIZONTAL LINE-->
<hr style="height:2px;border-width:0;color:#2C3E50;background-color:#2C3E50">



## **Computação estatística** {#computacao-estatistica}

<br>

<div><center>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Eficácia </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Efetividade </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Confiabilidade </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Concordância </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Acurácia </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Validade </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Desempenho diagnóstico </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Meta-análise </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Análise de redes </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Códigos em R </span>
</center></div>

<br>

### **`r library(fontawesome); fa("users", margin_right = "0.1em")` Estimativa de tamanho amostral**
<p>*Texto editável | R Script*</p>

### **`r library(fontawesome); fa("shuffle", margin_right = "0.1em")` Tabela de aleatorização em grupos**
<p>*Texto editável | R Script*</p>

### **`r library(fontawesome); fa("table", margin_right = "0.1em")` Modelagem de banco de dados**
<p>*Tabela editável | Formatação de tipos de variáveis | Validação de entrada de dados | Cálculo de variáveis secundárias *</p>

### **`r library(fontawesome); fa("file-lines", margin_right = "0.1em")` Plano de análise estatística**
<p>*Revisão de objetivos geral/específicos | Plano de análise em texto editável*</p>

### **`r library(fontawesome); fa("desktop", margin_right = "0.1em")` Simulação de estudos**
<p>*Texto editável | Tabela descritiva | Tabela/gráfico inferencial | R Script*</p>

### **`r library(fontawesome); fa("chalkboard-user", margin_right = "0.1em")` Mentoria**
<p>*Orientação*</p>

<!--script for generating HORIZONTAL LINE-->
<hr style="height:2px;border-width:0;color:#2C3E50;background-color:#2C3E50">



## **Computação biomédica** {#computacao-biomedica}

<br>

<div><center>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Eletromiografia de superfície </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Eletrogoniometria </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Posturografia </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Cinemetria </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Códigos em R </span>
</center></div>

<br>

### **`r library(fontawesome); fa("chalkboard-user", margin_right = "0.1em")` Mentoria**
<p>*Orientação*</p>

<!--script for generating HORIZONTAL LINE-->
<hr style="height:2px;border-width:0;color:#2C3E50;background-color:#2C3E50">



## **Submissão de manuscritos** {#manuscrito-submissao}

<br>

<div><center>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Artigo original </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Revisão de escopo </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Revisão sistemática </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Meta-análise</span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Revisão externa por pares </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Carta-resposta </span>
</center></div>

<br>

### **`r library(fontawesome); fa("clipboard-list", margin_right = "0.1em")` Revisão de métodos**
<p>*Texto editável | Referências sugeridas*</p>

### **`r library(fontawesome); fa("comment-dots", margin_right = "0.1em")` Revisão de estilo científico**
<p>*Texto editável | Referências sugeridas*</p>

### **`r library(fontawesome); fa("list-ol", margin_right = "0.1em")` Formatação de referências**
<p>*Texto editável | Biblioteca de software gerenciador*</p>

### **`r library(fontawesome); fa("chalkboard-user", margin_right = "0.1em")` Mentoria**
<p>*Orientação*</p>

<!--script for generating HORIZONTAL LINE-->
<hr style="height:2px;border-width:0;color:#2C3E50;background-color:#2C3E50">
