---
title: "**Serviços**"
link-citations: yes
output:
  html_document:
    toc: false
bibliography: references.bib
---

```{css, echo = FALSE}
body {
  font-size: 1.75em;
}

div.main-container {
  max-width: 1280px;
  margin-left: auto;
  margin-right: auto;
}

.center {
  margin-left: auto;
  margin-right: auto;
}
```

```{css, echo = FALSE}
.nav-pills>li>a:hover,
.nav-pills>li>a:focus,
.nav-pills>li.active>a,
.nav-pills>li.active>a:hover,
.nav-pills>li.active>a:focus{
   background-color: #2C3E50;
   }
.nav-pills > li {
    float:none;
    display:inline-block;
    zoom:1;
}
.nav-pills {
    text-align:center;
}
```

# {.tabset .tabset-fade .tabset-pills .tabset .justify-center}

## **Elaboração de projetos** {#projeto-de-pesquisa}

<div><center>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Objetivo geral </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Objetivos específicos </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Hipóteses </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Delineamento </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Aspectos éticos </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Critérios de elegibilidade </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Formatação </span>
</center></div>

<br>

<table style="width:100%">
  <tr>
    <td>
    
       <h3> **`r library(fontawesome); fa("clipboard-list", margin_right = "0.1em")` Revisão de métodos**</h3>
       <p>*Texto editável | Referências sugeridas*</p>
    
       <h3> **`r library(fontawesome); fa("comment-dots", margin_right = "0.1em")` Revisão de estilo científico**</h3>
       <p>*Texto editável | Referências sugeridas*</p>
    
       <h3> **`r library(fontawesome); fa("book-medical", margin_right = "0.1em")` Revisão de aspectos éticos**</h3>
       <p>*Texto editável*</p>
    
       <h3> **`r library(fontawesome); fa("list-ol", margin_right = "0.1em")` Formatação de referências**</h3>
       <p>*Texto editável | Biblioteca de software gerenciador*</p>
    
       <h3> **`r library(fontawesome); fa("chalkboard-user", margin_right = "0.1em")` Mentoria**</h3>
       <p>*Orientação*</p>
       
  </td>
    
  <td style="text-align:right;vertical-align:top">
  
    <a style="font-size:1em;border-width:3px;border-style: solid; border-color:white; border-radius:15px; padding:10px; background-color:red; text-decoration:none; color:white" href="mailto:cienciacomr@gmail.com?subject=Solicito um orçamento: Elaboração de projetos&body=Tema da sua pesquisa: %0D%0A %0D%0A %0D%0A Fale sobre o seu projeto: %0D%0A %0D%0A %0D%0A Prazo para conclusão da consultoria: %0D%0A %0D%0A %0D%0A Inclua arquivos em anexo %0D%0A %0D%0A %0D%0A"><b>Orçamento</b></a>
    
  </td>
</tr>
</table>

<br>

<br>

<br>

<br>

<!--script for generating HORIZONTAL LINE-->

<hr style="height:2px;border-width:0;color:#2C3E50;background-color:#2C3E50">

## **Computação estatística** {#computacao-estatistica}

<div><center>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Eficácia </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Efetividade </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Confiabilidade </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Concordância </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Acurácia </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Validade </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Desempenho diagnóstico </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Meta-análise </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Análise de redes </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Códigos em R </span>
</center></div>

<br>

<table style="width:100%">
  <tr>
    <td>
       
       <h3> **`r library(fontawesome); fa("users", margin_right = "0.1em")` Estimativa de tamanho amostral**</h3>
       <p>*Texto editável | R Script*</p>
       
       <h3> **`r library(fontawesome); fa("shuffle", margin_right = "0.1em")` Tabela de aleatorização em grupos**</h3>
       <p>*Texto editável | R Script*</p>
       
       <h3> **`r library(fontawesome); fa("table", margin_right = "0.1em")` Modelagem de banco de dados**</h3>
       <p>*Tabela editável | Formatação de tipos de variáveis | Validação de entrada de dados | Cálculo de variáveis secundárias *</p>
       
       <h3> **`r library(fontawesome); fa("file-lines", margin_right = "0.1em")` Plano de análise estatística**</h3>
       <p>*Revisão de objetivos geral/específicos | Plano de análise em texto editável*</p></h3>
       
       <h3> **`r library(fontawesome); fa("desktop", margin_right = "0.1em")` Simulação de estudos**</h3>
       <p>*Texto editável | Tabela descritiva | Tabela/gráfico inferencial | R Script*</p>
       
       <h3> **`r library(fontawesome); fa("chalkboard-user", margin_right = "0.1em")` Mentoria**</h3>
       <p>*Orientação*</p>

  </td>
    
  <td style="text-align:right;vertical-align:top">
  
    <a style="font-size:1em;border-width:3px;border-style: solid; border-color:white; border-radius:15px; padding:10px; background-color:red; text-decoration:none; color:white" href="mailto:cienciacomr@gmail.com?subject=Solicito um orçamento: Computação estatística&body=Tema da sua pesquisa: %0D%0A %0D%0A %0D%0A Fale sobre o seu projeto: %0D%0A %0D%0A %0D%0A Prazo para conclusão da consultoria: %0D%0A %0D%0A %0D%0A Inclua arquivos em anexo %0D%0A %0D%0A %0D%0A"><b>Orçamento</b></a>
    
  </td>
</tr>
</table>

<br>

<br>

<br>

<br>

<!--script for generating HORIZONTAL LINE-->

<hr style="height:2px;border-width:0;color:#2C3E50;background-color:#2C3E50">

## **Computação biomédica** {#computacao-biomedica}

<div><center>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Eletromiografia de superfície </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Eletrogoniometria </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Posturografia </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Cinemetria </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Códigos em R </span>
</center></div>

<br>

<table style="width:100%">
  <tr>
    <td>
       
       <h3> **`r library(fontawesome); fa("chalkboard-user", margin_right = "0.1em")` Mentoria** </h3>
       <p>*Orientação*</p>

  </td>
    
  <td style="text-align:right;vertical-align:top">
  
    <a style="font-size:1em;border-width:3px;border-style: solid; border-color:white; border-radius:15px; padding:10px; background-color:red; text-decoration:none; color:white" href="mailto:cienciacomr@gmail.com?subject=Solicito um orçamento: Computação biomédica&body=Tema da sua pesquisa: %0D%0A %0D%0A %0D%0A Fale sobre o seu projeto: %0D%0A %0D%0A %0D%0A Prazo para conclusão da consultoria: %0D%0A %0D%0A %0D%0A Inclua arquivos em anexo %0D%0A %0D%0A %0D%0A"><b>Orçamento</b></a>
    
  </td>
</tr>
</table>

<br>

<br>

<br>

<br>

<!--script for generating HORIZONTAL LINE-->

<hr style="height:2px;border-width:0;color:#2C3E50;background-color:#2C3E50">

## **Submissão de manuscritos** {#manuscrito-submissao}

<div><center>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Artigo original </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Revisão de escopo </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Revisão sistemática </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Meta-análise</span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Revisão externa por pares </span>
<span class="badge rounded-pill bg-primary" style="font-size:0.8em;"> Carta-resposta </span>
</center></div>

<br>

<table style="width:100%">
  <tr>
    <td>
       
       <h3> **`r library(fontawesome); fa("clipboard-list", margin_right = "0.1em")` Revisão de métodos** </h3>
       <p>*Texto editável | Referências sugeridas*</p>
       
       <h3> **`r library(fontawesome); fa("comment-dots", margin_right = "0.1em")` Revisão de estilo científico** </h3>
       <p>*Texto editável | Referências sugeridas*</p>
       
       <h3> **`r library(fontawesome); fa("list-ol", margin_right = "0.1em")` Formatação de referências** </h3>
       <p>*Texto editável | Biblioteca de software gerenciador*</p>
       
       <h3> **`r library(fontawesome); fa("chalkboard-user", margin_right = "0.1em")` Mentoria** </h3>
       <p>*Orientação*</p>

  </td>
  
  <td style="text-align:right;vertical-align:top">
  
    <a style="font-size:1em;border-width:3px;border-style: solid; border-color:white; border-radius:15px; padding:10px; background-color:red; text-decoration:none; color:white" href="mailto:cienciacomr@gmail.com?subject=Solicito um orçamento: Submissão de manuscritos&body=Tema da sua pesquisa: %0D%0A %0D%0A %0D%0A Fale sobre o seu projeto: %0D%0A %0D%0A %0D%0A Prazo para conclusão da consultoria: %0D%0A %0D%0A %0D%0A Inclua arquivos em anexo %0D%0A %0D%0A %0D%0A"><b>Orçamento</b></a>
    
  </td>
</tr>
</table>

<br>

<br>

<br>

<br>

<!--script for generating HORIZONTAL LINE-->

<hr style="height:2px;border-width:0;color:#2C3E50;background-color:#2C3E50">
